DROP DATABASE IF EXISTS JOIN_US;
CREATE DATABASE JOIN_US;
USE JOIN_US;

CREATE TABLE USERS(
    EMAIL VARCHAR(255) NOT NULL PRIMARY KEY,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT NOW()
);


INSERT INTO USERS(EMAIL) VALUES('xyz@gmail.com'),('abc@gmail.com');
SELECT * FROM USERS;
